model:
  training: refine
  spec_weight: ??? # path/to/spectrum_unet/weight when training is refine

optim:
  lr: 0.0004

loss:
  spec:
    norm: 1
    coef: 0.0
    cut_idx: 0
  valid:
    norm: 1
    coef: 1.0
  hole:
    norm: 1
    coef: 6.0
  tv:
    coef: 0.1
  perc:
    norm: 1
    coef: 0.05
  style:
    norm: 1
    coef: 120.0
