mode: test

defaults:
  - experiment: ???

model:
  arch: wnet # [wnet, spec_unet]
  num_layers: 5 # [5, 8]
  use_image: False
  unite_method: cat # [cat, pool_cat, ft_cat, prod, pool_prod, ft_prod]

input:
  img: ./data/1/img/_/valley_00001345.jpg
  mask: ./data/1/mask/1121.png

weight_path: ./
seed: null
gpu_id: 0